DROP TABLE ODONTOLOGOS IF EXISTS;
CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NROMATRICULA INT NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 23131,'JUAN','PEREZ'),(DEFAULT, 3213, 'NARUTO','UZUMAKI');